# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
 # contentDir = "content"

# Uncomment the lines below to configure your website in a second language.
[fr]
  languageCode = "fr-ch"

[[fr.menu.main]]
  name = "A propos"
  url = "#about"
  weight = 1

[[fr.menu.main]]
  name = "Experience"
  url = "#experience"
  weight = 2
  
[[fr.menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 4

[[fr.menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

  
[fr.params]
address = "Morges, Suisse"
contact_links = [
  {icon = "twitter", icon_pack = "fab", name = "Trouvez moi sur twitter", link = "https://twitter.com/JGustavsen"},
#  {icon = "skype", icon_pack = "fab", name = "Skype Me", link = "skype:echo123?call"},
#  {icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
#  {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  # {icon = "telegram", icon_pack = "fab", name = "Telegram Me", link = "https://telegram.me/@Telegram"},
  ]
